### ISSUE TITLE
number_to_words wrong for 0-prefixed numbers

### ISSUE THREAD

**Issue by albertz** [jaraco/inflect#105]
I would expect that `number_to_words("007")` returns `"zero zero seven"` but it returns just `"seven"`.

Maybe there is just an option for that behavior which I miss? Or I should use another function? If that functionality is already there, maybe that example could be added to the Readme.

Otherwise, I'm not really sure whether to treat this as a bug or as a feature request. But I would argue that this is a bug, because if I pass on a string, and it explicitly has a 0 prefix, I would expect that it does not ignore the zeros.

**Comment by hugovk** [comment]
All the examples in the README show `number_to_words` taking an integer as input.

How about this?

```pycon
>>> " ".join((p.number_to_words(x) for x in list("007")))
'zero zero seven'
```

**Comment by albertz** [comment]
Yes I know, but from the code it looked like a `str` as input is also ok.

**Comment by jaraco** [comment]
Another project, [num2words](/savoirfairelinux/num2words) has the same behavior:

```
$ num2words 007
seven
```

It seems to me the use-case you have here is peculiar to speaking each digit, including leading zeros and it seems like for that case, the example Hugo gave is just fine.

If you have a compelling reason why this library should specifically alliterate leading zeros, please share that rationale. Otherwise, I'm going to presume there's no further action needed here.
