### ISSUE TITLE
Document that this is for English only

### ISSUE THREAD

**Issue by sveinbjornt** [jaraco/inflect#209]
Neither the summary nor the README explicitly specifies that this is for English only. Would be helpful to clarify this in the documentation as there are many, many other languages in the world!

**Comment by jaraco** [comment]
That seems reasonable. Would you be interested in drafting the change?

**Comment by joshstephenson** [comment]
I'm happy to do that if you would like. It sounds like the kind of thing that belongs at the top of the README, under **NAME**. Perhaps...

**Instead of this:**
inflect.py - Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words.

**How about this:**
inflect.py - Accurately generate plurals, singular nouns, ordinals, indefinite articles, and word-based representations of numbers. This functionality is limited to English.

- I find that "accurate" sounds better than "correct" because correct should be a given.
- I removed the semicolon because after adding the disclaimer it would lead to ambiguity.
- I changed "convert numbers to words" to "word-based representations of numbers" so it flows naturally from "accurately generate...word-based representations of numbers." Another option here would be "number representations" but I like the clarity of the first option.

I hope this is satisfactory. Let me know if you'd like a PR with this change.
