### ISSUE TITLE
Singular words ending in s having their s removed by singular_noun

### ISSUE THREAD

**Issue by adiggsus** [jaraco/inflect#76]
I think this is a variation on #46.  A brief code sample:
for i in ['pancreas', 'mitosis', 'sepsis', 'assess', 'access', 'status', 'photolysis', 'actress']:
    print(p.singular_noun(i))

Kudos by the way for getting "status" correct - all of the other libraries I've worked with turn that into "statu", but the rest of these have 1 trailing s removed.  Particularly amusing to me is assess - the removal of the trailing s yields a legitimate plural of a different root word :)

Anyway - the best idea I've had for how to address this kind of problem, and I think something I can implement locally, is to check the word after singularization via a dictionary lookup, to see if it's a word (and preferably a singular word).  So "access" becoming "acces" would fail, and thus would be returned to "access".  I think that logic would work for many of the other common examples (such as "dress" becoming "dres") over in #46.

For the rather large collection of words from the science realm that are singular and end in a single s, I'm guessing that most dictionaries aren't going to have them, so this lookup idea will fail.  But it's at least something to try.

For my own use case, presuming that the input is plural to the singular_noun function is a very strong assumption, and may make the function unusable for my purposes.  I've got millions of words that I'm "stemming" by finding their singular form and storing them that way.  A variant of the function that takes a word and returns the singular form, whether it starts out as plural or singular, would be far more useful.  Returning False for words that aren't themselves plural probably enables me to develop my own function around singular_noun (it all depends on how consistently I get a correct reading on the plural state of the noun).

**Comment by hugovk** [comment]
```python
Python 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import inflect
>>> p = inflect.engine()
>>> for i in ['pancreas', 'mitosis', 'sepsis', 'assess', 'access', 'status', 'photolysis', 'actress']:
...     print(p.singular_noun(i))
...
pancrea
mitosi
sepsi
asses
acces
status
photolysi
actres
```

> The method ``singular_noun()`` takes a *plural* English noun or
 pronoun and returns its singular. Pronouns in the nominative ("we" ->
 "I") and accusative ("us" -> "me") cases are handled, as are
 possessive pronouns ("ours" -> "mine"). When third person
 singular pronouns are returned they take the neuter gender by default
 ("they" -> "it"), not ("they"-> "she") nor ("they" -> "he"). This can be
 changed with ``gender()``.

https://github.com/jazzband/inflect#forming-plurals-and-singulars

The current behaviour is kind of by design; junk in, junk out: don't give singulars to `singular_noun()`.

**Comment by rhalaly** [comment]
> don't give singulars to `singular_noun()`.

@hugovk, you not always knows if the word is singular. 
I use `singular_noun` to detect if word is singular, but it mistakes if the word ends with `s`.

**Comment by hugovk** [comment]
Sure, you don't always know, but neither does this library, and I understand it's been designed with the assumption that you do know.

**Comment by jaraco** [comment]
I note that the library doesn't handle plural forms of some of these words either:

```
>>> eng.singular_noun('pancreases')
'pancrease'
>>> eng.singular_noun('pancreata')
False
```

It does, however, handle actress and sepsis correctly:

```
>>> eng.singular_noun('actresses')
'actress'
>>> eng.plural('sepsis')
'sepses'
>>> eng.singular_noun('sepses')
'sepsis'
```

The reason it handles `status` correctly is because the plural of `status` is `status`.

I'd be happy to accept a pull request for plural forms of 'pancreas', but I don't think there's much this library can do in its current form to address the issue as reported.

If you believe there's a way that a library could or should support `singular_noun` accepting both singular and plural inputs, I'd be open to expanding the scope, but such a change would require some careful design. If anyone is up for that challenge, feel free to draft a proposal as a separate issue.

**Comment by jaraco** [comment]
Reviewing #15, I learned that the library intends to support `singular_noun` on singular nouns returning False. I've captured the expectation in 560b6f9 and added this list of incorrect words to that #15.
